Models/Calculadora.cs
namespace IntroViews.Models;

public class Calculadora{
    public string? Operacao{get; set;}
    public double Numero1{get; set;}
    public double Numero2{get; set;}
    public double Resultado{get; set;}
    public string? NomeOperacao{get; set;}
}

Models/ErrorViewModel.cs
namespace IntroViews.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/CalculadoraController.cs
using Microsoft.AspNetCore.Mvc;
using IntroViews.Models;


namespace IntroViews.Controllers;


public class CalculadoraController : Controller
{

    public IActionResult Calculadora()
    {
        return View();
    }

    public IActionResult Operacao([FromForm]string operacao, [FromForm]double numero1, [FromForm]double numero2)
    {
        var viewModel = new Calculadora()
        {
            Operacao = operacao,
            Numero1 = numero1,
            Numero2 = numero2,
            Resultado = 0,
            NomeOperacao = ""
        };

        if(viewModel.Operacao == "+")
        {
            viewModel.Resultado = viewModel.Numero1 + viewModel.Numero2;
            viewModel.NomeOperacao = "Soma";
            return View(viewModel);
        }
        else if(viewModel.Operacao == "-")
        {
            viewModel.Resultado = viewModel.Numero1 - viewModel.Numero2;
            viewModel.NomeOperacao = "Subtração";
            return View(viewModel);
        }
        else if(viewModel.Operacao == "*")
        {
            viewModel.Resultado = viewModel.Numero1 * viewModel.Numero2;
            viewModel.NomeOperacao = "Multiplicação";
            return View(viewModel);
        }
        else
        {
            viewModel.Resultado = viewModel.Numero1 / viewModel.Numero2;
            viewModel.NomeOperacao = "Divisão";
            return View(viewModel);
        }
    }

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using IntroViews.Models;

namespace IntroViews.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/OperacoesMatematicasController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using IntroViews.Models;

namespace IntroViews.Controllers;


public class OperacoesMatematicasController : Controller
{
    public IActionResult Somar()
    {
        return View();
    }

    public IActionResult Subtrair()
    {
        return View();
    }

    public IActionResult Multiplicar()
    {
        return View();
    }

    public IActionResult Dividir()
    {
        return View();
    }

    public IActionResult ResultadoSoma([FromForm]double n1, [FromForm]double n2){
        ViewBag.N1 = n1;
        ViewBag.N2 = n2;
        ViewBag.Resultado = n1 + n2;
        
        return View();
    }

    public IActionResult ResultadoSubtrair([FromForm]double n1, [FromForm]double n2){
        ViewBag.N1 = n1;
        ViewBag.N2 = n2;
        ViewBag.Resultado = n1 - n2;
        
        return View();
    }

    public IActionResult ResultadoMultiplicar([FromForm]double n1, [FromForm]double n2){
        ViewBag.N1 = n1;
        ViewBag.N2 = n2;
        ViewBag.Resultado = n1 * n2;
        
        return View();
    }

    public IActionResult ResultadoDividir([FromForm]double n1, [FromForm]double n2){
        ViewBag.N1 = n1;
        ViewBag.N2 = n2;
        ViewBag.Resultado = n1 / n2;
        
        return View();
    }


}

Views/Calculadora/Calculadora.cshtml
@{
    ViewData["Title"] = "Resultado";
}

<h1>Calculadora</h1>
<p>Utilize o formulário para realizar uma operação matemática</p>

<form action="/Calculadora/Operacao" method="POST">
    <label for="numero1">Número 1</label>
    <input type="text" id="numero1" name="numero1">

    <label for="numero2">Número 2</label>
    <input type="text" id="numero2" name="numero2">

    <label for="operacao">Operação</label>
    <select name="operacao" id="operacao">
        <option value="+">Somar</option>
        <option value="-">Subtrair</option>
        <option value="*">Multiplicar</option>
        <option value="/">Dividir</option>
    </select>

    <input class="submit" type="submit" value="Calcular">
</form>

Views/Calculadora/Operacao.cshtml
@model IntroViews.Models.Calculadora

@{
    ViewData["Title"] = "Operacao";
}

<h1>Resultado da @Model.NomeOperacao</h1>
<p>A @Model.NomeOperacao de @Model.Numero1 @Model.Operacao @Model.Numero2 é igual a @Model.Resultado</p>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/OperacoesMatematicas/Dividir.cshtml
@{
    ViewData["Title"] = "Dividir";
}

<h1>Dividir</h1>

<form action="/OperacoesMatematicas/ResultadoDividir" method="POST">
    <label for="n1">Numero 1</label>
    <input type="text" id="n1" name="n1">

    <label for="n2">Numero 2</label>
    <input type="text" id="n2" name="n2">

    <input type="submit" value="Dividir">
</form>

Views/OperacoesMatematicas/Multiplicar.cshtml
@{
    ViewData["Title"] = "Multiplicar";
}

<h1>Multiplicar</h1>

<form action="/OperacoesMatematicas/ResultadoMultiplicar" method="POST">
    <label for="n1">Numero 1</label>
    <input type="text" id="n1" name="n1">

    <label for="n2">Numero 2</label>
    <input type="text" id="n2" name="n2">

    <input type="submit" value="Multiplicar">
</form>

Views/OperacoesMatematicas/ResultadoDividir.cshtml
@{
    ViewData["Title"] = "Resultado Dividir";
}

<h1>Resultado da Dividir</h1>
<p>A divisão de @ViewBag.N1 / @ViewBag.N2 é igual a @ViewBag.Resultado</p>

Views/OperacoesMatematicas/ResultadoMultiplicar.cshtml
@{
    ViewData["Title"] = "Resultado Multiplicar";
}

<h1>Resultado da Multiplicação</h1>
<p>A multiplicação de @ViewBag.N1 * @ViewBag.N2 é igual a @ViewBag.Resultado</p>

Views/OperacoesMatematicas/ResultadoSoma.cshtml
@{
    ViewData["Title"] = "Resultado Soma";
}

<h1>Resultado da Soma</h1>
<p>A soma de @ViewBag.N1 + @ViewBag.N2 é igual a @ViewBag.Resultado</p>

Views/OperacoesMatematicas/ResultadoSubtrair.cshtml
@{
    ViewData["Title"] = "Resultado Subtrair";
}

<h1>Resultado da Soma</h1>
<p>A soma de @ViewBag.N1 - @ViewBag.N2 é igual a @ViewBag.Resultado</p>

Views/OperacoesMatematicas/Somar.cshtml
@{
    ViewData["Title"] = "Somar";
}

<h1>Somar</h1>

<form action="/OperacoesMatematicas/ResultadoSoma" method="POST">
    <label for="n1">Numero 1</label>
    <input type="text" id="n1" name="n1">

    <label for="n2">Numero 2</label>
    <input type="text" id="n2" name="n2">

    <input type="submit" value="Somar">
</form>

Views/OperacoesMatematicas/Subtrair.cshtml
@{
    ViewData["Title"] = "Subtrair";
}

<h1>Subtrair</h1>

<form action="/OperacoesMatematicas/ResultadoSubtrair" method="POST">
    <label for="n1">Numero 1</label>
    <input type="text" id="n1" name="n1">

    <label for="n2">Numero 2</label>
    <input type="text" id="n2" name="n2">

    <input type="submit" value="Subtrair">
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IntroViews</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IntroViews.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IntroViews</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculadora" asp-action="Calculadora">Calculadora</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - IntroViews - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>